nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['POST', 'GET']
        allow_headers: ['Content-Type', 'X-User-Ip']
        max_age: 3600
    paths:
        '^/': null
